#!/bin/bash
# amalgamate.sh -- Create a single-file amalgamation of Litesrpent
#
# Produces build/litesrpent.c containing ALL source code in one file,
# similar to how SQLite distributes sqlite3.c.
#
# Uses Git Bash tools (cat, sed, awk, sort) as requested.

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INC="$PROJECT_ROOT/include"
SRC="$PROJECT_ROOT/src"
OUT="$PROJECT_ROOT/build/litesrpent.c"

mkdir -p "$PROJECT_ROOT/build"

echo "Amalgamating Litesrpent into a single C file..."

# Ordered list of headers (dependency order matters)
HEADERS=(
    "$INC/litesrpent.h"
    "$INC/lscore.h"
    "$INC/lseval.h"
    "$INC/lsopcodes.h"
)

# Ordered list of source files
SOURCES=(
    "$SRC/lscore.c"
    "$SRC/lsgc.c"
    "$SRC/lsenv.c"
    "$SRC/lsreader.c"
    "$SRC/lsprinter.c"
    "$SRC/lseval.c"
    "$SRC/lsbuiltins.c"
    "$SRC/lsclos.c"
    "$SRC/lsvm.c"
    "$SRC/lsaot.c"
    "$SRC/lsjit.c"
    "$SRC/lsffi.c"
    "$SRC/lsgui.c"
    "$SRC/lsgl.c"
    "$SRC/lsvk.c"
    "$SRC/lself.c"
    "$SRC/main.c"
)

# Start the amalgamation
cat > "$OUT" <<'AMALG_HEADER'
/***********************************************************************
 * litesrpent.c -- Amalgamated single-file build of Litesrpent
 *
 * This file is auto-generated by tools/amalgamate.sh.
 * Do NOT edit this file directly; edit the individual source files
 * under src/ and include/ and re-run the amalgamation.
 *
 * Litesrpent is a Common Lisp implementation in C featuring:
 *   - REPL / tree-walking interpreter
 *   - Bytecode compiler + VM
 *   - AOT compilation (transpile to C, invoke gcc)
 *   - x86-64 JIT compiler
 *   - FFI (LoadLibrary / dlopen)
 *   - Win32 GUI bindings
 *   - OpenGL bindings
 *   - Vulkan bindings
 *   - CLOS and condition system
 *   - ELF / PE binary writers
 *
 * Compile with:
 *   gcc -O2 -o litesrpent litesrpent.c -lm -lkernel32 -luser32 -lgdi32
 *
 ***********************************************************************/
AMALG_HEADER

echo "" >> "$OUT"
echo "/* ===== Standard library includes ===== */" >> "$OUT"
echo "#include <stdio.h>" >> "$OUT"
echo "#include <stdlib.h>" >> "$OUT"
echo "#include <string.h>" >> "$OUT"
echo "#include <stdint.h>" >> "$OUT"
echo "#include <stdarg.h>" >> "$OUT"
echo "#include <setjmp.h>" >> "$OUT"
echo "#include <ctype.h>" >> "$OUT"
echo "#include <math.h>" >> "$OUT"
echo "#include <time.h>" >> "$OUT"
echo "#include <assert.h>" >> "$OUT"
echo "#include <errno.h>" >> "$OUT"
echo "#include <inttypes.h>" >> "$OUT"
echo "#ifdef _WIN32" >> "$OUT"
echo "#define WIN32_LEAN_AND_MEAN" >> "$OUT"
echo "#include <windows.h>" >> "$OUT"
echo "#else" >> "$OUT"
echo "#include <sys/mman.h>" >> "$OUT"
echo "#include <dlfcn.h>" >> "$OUT"
echo "#endif" >> "$OUT"
echo "" >> "$OUT"

# Emit headers, stripping their #include of each other and include guards
echo "/* ===== Amalgamated headers ===== */" >> "$OUT"
for hdr in "${HEADERS[@]}"; do
    hdr_base=$(basename "$hdr")
    echo "" >> "$OUT"
    echo "/*** Begin: $hdr_base ***/" >> "$OUT"
    # Strip: #include "litesrpent.h", #include "lscore.h", etc.
    # Strip: #ifndef/#define/#endif include guards
    sed -E \
        -e '/^#include "[^"]*"$/d' \
        -e '/^#ifndef LS_/d' \
        -e '/^#define LS_.*_H$/d' \
        -e '/^#endif/d' \
        -e '/^#ifndef LITESRPENT_H$/d' \
        -e '/^#define LITESRPENT_H$/d' \
        -e '/^#ifdef __cplusplus$/d' \
        -e '/^extern "C" \{$/d' \
        -e '/^\}$/d' \
        "$hdr" >> "$OUT"
    echo "/*** End: $hdr_base ***/" >> "$OUT"
done

echo "" >> "$OUT"
echo "/* ===== Amalgamated source files ===== */" >> "$OUT"

for src in "${SOURCES[@]}"; do
    src_base=$(basename "$src")
    echo "" >> "$OUT"
    echo "/*** Begin: $src_base ***/" >> "$OUT"
    # Strip local #include "..." lines (already included above)
    sed -E \
        -e '/^#include "[^"]*"$/d' \
        -e '/^#include <(stdio|stdlib|string|stdint|stdarg|setjmp|ctype|math|time|assert|errno|inttypes)\.h>$/d' \
        -e '/^#define WIN32_LEAN_AND_MEAN$/d' \
        -e '/^#include <windows\.h>$/d' \
        -e '/^#include <sys\/mman\.h>$/d' \
        -e '/^#include <dlfcn\.h>$/d' \
        "$src" >> "$OUT"
    echo "/*** End: $src_base ***/" >> "$OUT"
done

# Count lines
TOTAL=$(wc -l < "$OUT")
SIZE=$(du -h "$OUT" | cut -f1)

echo ""
echo "Amalgamation complete:"
echo "  Output: $OUT"
echo "  Lines:  $TOTAL"
echo "  Size:   $SIZE"
echo ""
echo "To compile the amalgamation directly:"
echo "  gcc -O2 -o litesrpent build/litesrpent.c -lm -lkernel32 -luser32 -lgdi32"
